springdoc:
  swagger-ui:
    tryItOutEnabled: true
    filter: true
    path: /swagger-ui

server:

  servlet:
    context-path: /api

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otus-demo?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  liquibase:
    change-log: liquibase/master.xml
    enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

otus:
  rabbitmq:
    exchange: super-otus.exchange
    routingkey: super.otus
    queue: super-otus.queue